# Generated by Django 2.0.2 on 2018-10-02 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.CharField(db_index=True, max_length=500, verbose_name='Description')),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Listed Item',
                'verbose_name_plural': 'Listed Items',
            },
        ),
        migrations.CreateModel(
            name='Postit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Postit',
                'verbose_name_plural': 'Postits',
            },
        ),
        migrations.AddField(
            model_name='listitem',
            name='postit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='list_items', to='postit.Postit', verbose_name='Postit'),
        ),
    ]
